### ISSUE TITLE
Netbeans 12 support

### ISSUE THREAD

**Issue by bobbotron** [manikantannaren/mynetbeans#40] opened 2020-12-03 14:55 UTC
Hi there, is there any chance of adding support for netbeans 12?  Can I help with the update?  This is a handy plugin, I used to us it a lot.

**Comment by ilgrosso** [comment] 2020-12-31 09:22
Same here, pleas react.

**Comment by manikantannaren** [comment] 2021-01-03 15:14
Duplicate of Issue #36

**Closed as completed by manikantannaren** 2021-01-03 15:14 UTC
